# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo pip install ansible-playbook
    echo ansible-playbook -i hosts inventory.yaml
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
